# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import Qt
from PyQt5 import QtCore,QtWidgets
from PyQt5.QtGui import QTextOption,  QKeySequence
from PyQt5.QtWidgets import QTextEdit, QApplication


class MyTextEdit(QTextEdit):
    def keyPressEvent(self, event):
        if event.matches(QKeySequence.Paste):
            clipboard = QApplication.clipboard()
            text = clipboard.text()
            self.insertPlainText(text)
            # 在这里添加你想要执行的操作
        else:
            super().keyPressEvent(event)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(860, 448)

        self.button_preview = QtWidgets.QPushButton(Form)
        self.button_preview.setGeometry(QtCore.QRect(350, 230, 75, 23))
        self.button_preview.setObjectName("button_preview")
        self.text_edit = MyTextEdit(Form)
        self.text_edit.setGeometry(QtCore.QRect(20, 40, 281, 381))
        self.text_edit.setObjectName("text_edit")
        self.text_edit.setWordWrapMode(QTextOption.WrapAnywhere)
        self.text_browser_right = QtWidgets.QTextBrowser(Form)
        self.text_browser_right.setGeometry(QtCore.QRect(480, 40, 202, 381))
        self.text_browser_right.setObjectName("text_browser_right")
        self.text_browser_right.setTextInteractionFlags(Qt.TextEditable|Qt.TextSelectableByMouse|Qt.LinksAccessibleByMouse)
        self.text_browser_right.setFontPointSize(20)
        self.text_option = QTextOption()
        self.text_option.setWrapMode(QTextOption.WrapAnywhere)
        self.text_option_left = QTextOption()
        self.text_option_left.setWrapMode(QTextOption.WrapAtWordBoundaryOrAnywhere)
        self.spinbox_font = QtWidgets.QSpinBox(Form)
        self.spinbox_font.setGeometry(QtCore.QRect(360, 120, 81, 22))
        self.spinbox_font.setMinimum(0)
        self.spinbox_font.setSingleStep(1)
        self.spinbox_font.setProperty("value", 9)
        self.spinbox_font.setObjectName("spinbox_font")
        self.label_font = QtWidgets.QLabel(Form)
        self.label_font.setGeometry(QtCore.QRect(325, 124, 54, 12))
        self.label_font.setObjectName("label_font")
        self.label_width = QtWidgets.QLabel(Form)
        self.label_width.setGeometry(QtCore.QRect(325, 164, 54, 12))
        self.label_width.setObjectName("label_width")
        self.spinbox_width = QtWidgets.QSpinBox(Form)
        self.spinbox_width.setGeometry(QtCore.QRect(360, 160, 81, 22))
        self.spinbox_width.setMinimum(0)
        self.spinbox_width.setMaximum(1000)
        self.spinbox_width.setObjectName("spinbox_width")
        self.spinbox_width.setProperty("value", 206)
        self.spinbox_width.setSingleStep(1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "文本预览"))
        self.button_preview.setText(_translate("Form", "预览"))
        self.label_font.setText(_translate("Form", "字号："))
        self.label_width.setText(_translate("Form", "宽度"))
